// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXTKliu9VbdtctU5xrUNQgTF1PDX7AGM',
    appId: '1:279501522890:web:4460c7fc810c6504f73133',
    messagingSenderId: '279501522890',
    projectId: 'main-9c09c',
    authDomain: 'main-9c09c.firebaseapp.com',
    storageBucket: 'main-9c09c.firebasestorage.app',
    measurementId: 'G-WJ3DVWVVJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDntPSf50y9_F1JuRvqxUH-vRvcZq65A',
    appId: '1:279501522890:android:d71f1f44abe6fe67f73133',
    messagingSenderId: '279501522890',
    projectId: 'main-9c09c',
    storageBucket: 'main-9c09c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpA2CGXIJMSb-w0EqKjSXe07y4yLWBl4',
    appId: '1:279501522890:ios:adc1d96673e679e2f73133',
    messagingSenderId: '279501522890',
    projectId: 'main-9c09c',
    storageBucket: 'main-9c09c.firebasestorage.app',
    iosBundleId: 'uz.otabek.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpA2CGXIJMSb-w0EqKjSXe07y4yLWBl4',
    appId: '1:279501522890:ios:adc1d96673e679e2f73133',
    messagingSenderId: '279501522890',
    projectId: 'main-9c09c',
    storageBucket: 'main-9c09c.firebasestorage.app',
    iosBundleId: 'uz.otabek.main',
  );
}
